### ISSUE TITLE
Rendering errors due to missing files/YAML adaptation

### ISSUE THREAD

**Issue by mkalz** [theResearchMethodBook/chapter-template#1]
The current version leads to rendering errors in R-Studio (Version 2023.06.0+421) on Mac OSX with Quarto. Two things required to make it work for me:

1. According to [https://quarto.org/docs/books/book-structure.html](https://quarto.org/docs/books/book-structure.html) an index.qmd is required.
2. The YAML also needs to have a reference to index.qmd

**Comment by phish108** [comment]
fixed
